apiVersion: v1
kind: Service
metadata:
  name: jenkins-lab-service
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30050
